### ISSUE TITLE
do you have transform class : test data should not take part in creation of discreisation  intervals

### ISSUE THREAD

**Issue by Sandy4321** [Morgan243/PyCAIM#2]
do you have only fit class , since transform class needed as well
main idea is to create discreisation by train data and then use it for test data
so test data should not take part in creation of discreisation  intervals 
how different this from 
https://github.com/airysen/caimcaim
did you compared ?
do you have description for unpublished CAIM+??

**Comment by Morgan243** [comment]
@Sandy4321 I have not looked closely at [caimaim](https://github.com/airysen/caimcaim), but it looks like it was implemented after this repository. 

This implementation has a `predict` method for test-time discretization. Check the main block for execution from CLI as a usage example.
